### PR TITLE
Power requests, delay before reenabling sleep, further improvements

### PR DESCRIPTION
**Pull request by jonschz**
A number of new features have been contributed by @qwerty12 in #1. As noted in that pull request, here are some things to check before merging:
- ~Write our own wrapper for PowerRequests if its isn't too much work~
   Update: As it is right now, the library adds hardly any overhead at all (I measured 5KB in a test file). It looks reliable, I will only get rid of some linter issues and work out license stuff if needed (Vanara P/Invoke is MIT licensed).
- See if there is an easier solution to the Android app issue - I will also try to reproduce it
- Possible throttling of `SessionManager_PlaybackProgress`, this is something I noticed as well

### CODE REVIEW

**Comment by jonschz** [comment]
Progress:
- [x] Error handling
- [x] Logging simplification
- [ ] Configurable delay (#3 )
- [ ] Android issue
- [ ] Possible throttling

**Comment by jonschz** [comment]
@qwerty12 I have the following idea to implement the throttling:
- We add a new variable like `_lastCheckin`
- In `PlaybackProgress` we update `_lastCheckin` to `e.Session.LastPlaybackCheckIn` if the latter is more recent
- We add a global timer that checks every 10-ish seconds if `Now - _lastCheckin > sleepDelay`, and clears the PowerRequest if so
- The odds of problematic race conditions are quite low; the worst that could happen is two threads wanting to update `_lastCheckin` but only one of them being successful.

The main benefit would be that the function calls made in `PlaybackProgress` would be quite cheap. In particular, we would no longer call `Timer.Change` multiple times per second. What do you think?

**Comment by qwerty12** [comment]
(Sorry, I didn't realise I could actually check tickboxes in this repo on comments that aren't mine. An odd feeling :-))

I like the idea. The best I could come up with was the standard approach, which seems less efficient compared to your method.

**Comment by jonschz** [comment]
@qwerty12 The way I see it, this is ready to merge. Did you encounter any problems while testing the latest commit? If not, I'd merge this and create a new release.

**Comment by qwerty12** [comment]
In regards to testing on my computer, I have not run into any problems. I haven't really used my phone much to watch stuff via Jellyfin, sorry, so I can't really give you a conclusive result but on the few occasions I did, I didn't observe any issues there, either.

**Pull request merged**
